import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import { readFile } from "node:fs/promises";
import path from "node:path";
import bs58 from "bs58";
import type { Idl } from "@coral-xyz/anchor";

/**
 * ZK-compressed on-chain receipt client (the aemulus-zk-receipts Light program,
 * see anchor-zk/). Records a completed run's receipt as a *compressed* account
 * via Light Protocol's ZK Compression — ~100x cheaper than the rent-bearing PDA
 * the aemulus-registry program uses (~0.000015 vs ~0.0016 SOL), with a 128-byte
 * ZK validity proof verified on-chain. That makes a per-run on-chain receipt
 * economical at scale and is the "real ZK" backing the moat.
 *
 * Gated + inert exactly like the other on-chain paths: does nothing unless the
 * program id, a payer secret, AND a ZK-compression RPC (Helius/Photon) are all
 * configured, and the built program IDL is present.
 *
 * ⚠️ VERIFICATION STATUS: the Rust program is cargo-check verified. This client
 * follows Light's official TypeScript client guide, but the exact validity-proof
 * / packed-tree-info / IDL-encoding shapes can only be confirmed against the
 * built IDL on a live ZK-compression RPC (devnet). Validate there before mainnet.
 * Every such line is marked "// DEVNET" below.
 */

const SEND_TIMEOUT_MS = 60_000;

/** Path to the Anchor-built IDL (generated by `anchor build` in anchor-zk/). */
function idlPath(): string {
  return (
    process.env.AEMULUS_ZK_IDL ||
    path.join("anchor-zk", "target", "idl", "aemulus_zk_receipts.json")
  );
}

export function zkReceiptsEnabled(): boolean {
  return (
    !!process.env.AEMULUS_ZK_PROGRAM &&
    !!process.env.AEMULUS_ZK_SECRET &&
    !!process.env.AEMULUS_ZK_RPC
  );
}

function bytes32(hex: string | null | undefined): number[] {
  const out = Buffer.alloc(32);
  if (hex) Buffer.from(hex.replace(/^0x/, ""), "hex").copy(out, 0, 0, 32);
  return Array.from(out);
}
function outcomeCode(status: string | null): number {
  return status === "achieved" ? 1 : status === "unconfirmed" ? 2 : 0;
}

/**
 * Record a completed run's receipt as a ZK-compressed account. Returns the tx
 * signature, the derived compressed-account address, and the cluster — or null
 * if disabled / not yet built / it fails. Best-effort: callers fire-and-forget,
 * so a chain hiccup never affects the run.
 */
export async function recordRunCompressed(run: {
  receiptHash: string | null;
  commitmentRoot: string | null;
  outcomeStatus: string | null;
}): Promise<{ sig: string; address: string; cluster: string } | null> {
  if (!zkReceiptsEnabled() || !run.receiptHash) return null;

  // The IDL is required to encode the instruction; without it (program not yet
  // built) we stay inert rather than guess the layout.
  let idl: { address?: string };
  try {
    idl = JSON.parse(await readFile(path.resolve(process.cwd(), idlPath()), "utf8"));
  } catch {
    return null;
  }

  // Heavy Light + Anchor deps are loaded ONLY when this path is actually used,
  // so the default build never pulls them in.
  const light = await import("@lightprotocol/stateless.js");
  const anchor = await import("@coral-xyz/anchor");

  // Single source of truth for the program id: the IDL's `address` is what
  // anchor.Program dispatches to AND what the on-chain program derives its
  // compressed addresses under (&crate::ID), so we must derive with the SAME id.
  // Fall back to the env var only if the IDL somehow omits it.
  const programId = new PublicKey(idl.address || process.env.AEMULUS_ZK_PROGRAM!);
  const payer = Keypair.fromSecretKey(bs58.decode(process.env.AEMULUS_ZK_SECRET!));
  const cluster = process.env.AEMULUS_RECEIPT_CLUSTER || "mainnet-beta";
  const rpcUrl = process.env.AEMULUS_ZK_RPC!;

  // A ZK-compression RPC (Helius/Photon) serves both the Solana RPC and the
  // compression indexer + prover endpoints.
  const rpc = light.createRpc(rpcUrl, rpcUrl, rpcUrl, { commitment: "confirmed" });

  const receiptHash = bytes32(run.receiptHash);
  const commitmentRoot = bytes32(run.commitmentRoot);
  const outcome = outcomeCode(run.outcomeStatus);

  // One compressed account per receipt hash — same seeds as the program's
  // derive_address(&[b"receipt", receipt_hash], ...).
  const addressTree = new PublicKey(light.batchAddressTree); // v2 address tree // DEVNET
  const seed = light.deriveAddressSeedV2([
    Uint8Array.from(Buffer.from("receipt")),
    Uint8Array.from(receiptHash),
  ]);
  const address = light.deriveAddressV2(seed, addressTree, programId);

  // All network work (the validity-proof round-trip AND the send) runs inside
  // one timed block so a slow/hung compression RPC can't pin the worker - the
  // proof request was previously unbounded, before the timeout was armed.
  const work = (async (): Promise<{ sig: string; address: string; cluster: string }> => {
    // Prove the new address doesn't already exist (creation path). // DEVNET
    const proof = await rpc.getValidityProofV0(
      [],
      [{ tree: addressTree, queue: addressTree, address: light.bn(address.toBytes()) }],
    );

    // Pack the Light system accounts + address tree into remaining accounts. // DEVNET
    const systemConfig = light.SystemAccountMetaConfig.new(programId);
    const packed = new light.PackedAccounts();
    packed.addSystemAccountsV2(systemConfig);
    const treeIndex = packed.insertOrGet(addressTree);
    const outputStateTreeIndex = packed.insertOrGet(new PublicKey(light.batchMerkleTree)); // DEVNET
    const addressTreeInfo = {
      rootIndex: proof.rootIndices[0],
      addressMerkleTreePubkeyIndex: treeIndex,
      addressQueuePubkeyIndex: treeIndex,
    };

    const wallet = new anchor.Wallet(payer);
    const connection = new Connection(rpcUrl, "confirmed");
    const provider = new anchor.AnchorProvider(connection as never, wallet, {
      commitment: "confirmed",
    });
    const program = new anchor.Program(idl as Idl, provider);

    const sig = await (
      program.methods as Record<
        string,
        (...a: unknown[]) => {
          accounts: (a: unknown) => {
            remainingAccounts: (a: unknown) => { rpc: () => Promise<string> };
          };
        }
      >
    )
      .recordReceipt(
        proof.compressedProof, // ValidityProof // DEVNET
        addressTreeInfo,
        outputStateTreeIndex,
        receiptHash,
        commitmentRoot,
        outcome,
      )
      .accounts({ payer: payer.publicKey })
      .remainingAccounts(packed.toAccountMetas().remainingAccounts)
      .rpc();

    return { sig, address: address.toString(), cluster };
  })();
  // If the timeout wins the race, `work` is abandoned; swallow any later
  // rejection so it can't surface as an unhandledRejection.
  work.catch(() => {});

  let timer: ReturnType<typeof setTimeout> | undefined;
  const timeout = new Promise<null>((res) => {
    timer = setTimeout(() => res(null), SEND_TIMEOUT_MS);
  });
  try {
    return await Promise.race([work, timeout]);
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}
